kind: RoleBinding
apiVersion: rbac.authorization.k8s.io/v1
metadata:
  name: vol-postgres
subjects:
- kind: ServiceAccount
  name: vol-postgres
roleRef:
  kind: Role
  name: vol-postgres
  apiGroup: rbac.authorization.k8s.io
- kind: User
  name: jane # Name is case sensitive
  apiGroup: rbac.authorization.k8s.io
roleRef:
  kind: Role
  name: vol-postgres
  apiGroup: rbac.authorization.k8s.io
