apiVersion: apiextensions.k8s.io/v1beta1
kind: CustomResourceDefinition
metadata:
  name: postgresqls.postgres.example.com
spec:
  group: postgres.example.com
  names:
    kind: Postgresql
    listKind: PostgresqlList
    plural: postgresqls
    singular: postgresql
  scope: Namespaced
  subresources:
    status: {}
  versions:
  - name: v1alpha1
    served: true
    storage: true
