kind: RoleBinding
apiVersion: rbac.authorization.k8s.io/v1
metadata:
  name: adv-postgres
subjects:
- kind: ServiceAccount
  name: adv-postgres
roleRef:
  kind: Role
  name: adv-postgres
  apiGroup: rbac.authorization.k8s.io
