apiVersion: apiextensions.k8s.io/v1beta1
kind: CustomResourceDefinition
metadata:
  name: postgresadvs.postgres.example.com
spec:
  group: postgres.example.com
  names:
    kind: PostgresAdv
    listKind: PostgresAdvList
    plural: postgresadvs
    singular: postgresadv
  scope: Namespaced
  subresources:
    status: {}
  versions:
  - name: v1alpha1
    served: true
    storage: true
