kind: PersistentVolume
apiVersion: v1
metadata:
  name: postgresql-pv-volume
  labels:
    type: local
    app: postgresql
spec:
  storageClassName: manual
  capacity:
     storage: 2Gi
  accessModes:
    - ReadWriteMany
  hostPath:
    path: "/mnt/data"
---
kind: PersistentVolumeClaim
apiVersion: v1
metadata:
  name: postgresql-pv-volume-claim
  labels:
    type: local
    app: postgresql
spec:
  resources:
    requests:
      storage: 2Gi
  accessModes:
    - ReadWriteMany
